# Generated by Marten 0.5.2 on 2024-09-23 10:13:56 +03:00

class Migration::Management::V202409231013561 < Marten::Migration
  def plan
    create_table :management_batch do
      column :id, :big_int, primary_key: true, auto: true
      column :name, :string, max_size: 255, unique: true, index: true
      column :status, :string, max_size: 255, null: false, index: true, default: "active"
      column :created_at, :date_time
      column :updated_at, :date_time
    end
  end
end
