app = 'kebabkhana'
primary_region = 'otp'

[build]

[env]
  MARTEN_ALLOWED_HOSTS = "kebabkhana.fly.dev,kebabkhana.online,https://kebabkhana.online"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "bin/manage migrate"
