# fly.toml app configuration file generated for kebabkhana on 2024-10-02T23:42:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kebabkhana'
primary_region = 'otp'

[build]

[env]
  MARTEN_ALLOWED_HOSTS = "kebabkhana.fly.dev,kebabkhana.online"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "bin/manage migrate"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

