service: kebabkhana

image: hamaschwany/kebabkhana

ssh:
  user: root

servers:
  web:
    hosts:
      - 188.245.127.20

deploy_timeout: 60
drain_timeout: 30
readiness_delay: 30

proxy:
  ssl: true
  host: kebabkhana.hamaschwany.dev
  app_port: 3000
  healthcheck:
    interval: 15
    timeout: 15

registry:
  username:
    - KEBABKHANA__KAMAL__REGISTRY_USERNAME
  password:
    - KEBABKHANA__KAMAL__REGISTRY_PASSWORD

builder:
  arch: amd64
  secrets:
    - KEBABKHANA__SELF__ALLOWED_HOSTS
    - KEBABKHANA__SELF__SECRET_KEY_BASE
    - KEBABKHANA__DATABASE__URL
    - KEBABKHANA__ZOHO__EMAIL
    - KEBABKHANA__ZOHO__PASSWORD
    - KEBABKHANA__OTP__BASE_URL
    - KEBABKHANA__OTP__API_KEY
    - KEBABKHANA__OTP__SERVICE_ID

env:
  secret:
    - KEBABKHANA__DATABASE__URL
    - KEBABKHANA__KAMAL__REGISTRY_PASSWORD
    - KEBABKHANA__KAMAL__REGISTRY_USERNAME
    - KEBABKHANA__SELF__URL
    - KEBABKHANA__SELF__ALLOWED_HOSTS
    - KEBABKHANA__SELF__SECRET_KEY_BASE
    - KEBABKHANA__ZOHO__EMAIL
    - KEBABKHANA__ZOHO__PASSWORD
    - KEBABKHANA__OTP__BASE_URL
    - KEBABKHANA__OTP__API_KEY
    - KEBABKHANA__OTP__SERVICE_ID

# accessories:
#   postgres:
#     image: postgres:16
#     role: web
#     env:
#       secret:
#         - POSTGRES_PASSWORD
#         - POSTGRES_USER
#         - POSTGRES_DB
#     files:
#       - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/postgresql/data
