service: kebabkhana

image: hamaschwany/kebabkhana

ssh:
  user: root

servers:
  web:
    hosts:
      - 142.132.228.173

deploy_timeout: 60
drain_timeout: 30
readiness_delay: 30

proxy:
  ssl: true
  host: kebabkhana.online
  app_port: 3000
  healthcheck:
    interval: 15
    timeout: 15

registry:
  username:
    - KAMAL__REGISTRY_USERNAME
  password:
    - KAMAL__REGISTRY_PASSWORD

builder:
  arch: amd64
  secrets:
    - SELF__ALLOWED_HOSTS
    - SELF__SECRET_KEY_BASE
    - DATABASE__URL

env:
  secret:
    - DATABASE__URL
    - KAMAL__REGISTRY_PASSWORD
    - KAMAL__REGISTRY_USERNAME
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_HOST
    - POSTGRES_DATABASE
    - SELF__URL
    - SELF__ALLOWED_HOSTS
    - SELF__SECRET_KEY_BASE

accessories:
  postgres:
    image: postgres:16
    host: 142.132.228.173
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
