# Generated by Marten 0.5.2 on 2024-09-22 20:14:13 +03:00

class Migration::Auth::V202409222014131 < Marten::Migration
  replaces :auth, "0001_create_auth_user_table"

  def plan
    create_table :auth_user do
      column :id, :big_int, primary_key: true, auto: true
      column :email, :string, max_size: 254, unique: true
      column :password, :string, max_size: 128
      column :created_at, :date_time
      column :updated_at, :date_time
      column :first_name, :string, max_size: 128
      column :last_name, :string, max_size: 128
    end
  end
end
