# Generated by Marten 0.5.2 on 2025-05-21 16:00:50 +03:00

class Migration::Auth::V202505211600501 < Marten::Migration
  depends_on :auth, "0001_create_auth_user_table"

  def plan
    add_column :auth_user, :phone_number, :string, max_size: 128, default: ""

    add_column :auth_user, :is_phone_verified, :bool, default: false

    add_column :auth_user, :phone_verification_challenge, :string, max_size: 128, default: ""
  end
end
