# Generated by Marten 0.5.2 on 2024-09-28 11:52:59 +03:00

class Migration::Main::V202409281059135 < Marten::Migration
  depends_on :main, "202409281059131_create_main_order_table"
  depends_on :management, "202409241627099_create_management_item_table"

  def plan
    create_table :main_order_item do
      column :id, :big_int, primary_key: true, auto: true
      column :quantity, :int, default: 1
      column :total, :int, default: 0
      column :order_id, :reference, to_table: :main_order, to_column: :id
      column :item_id, :reference, to_table: :management_item, to_column: :id
      column :created_at, :date_time
      column :updated_at, :date_time
    end
  end
end
